### ISSUE TITLE
Invalid status code?

### ISSUE THREAD

**Issue by antoniobenedetti** [cuonic/SolusVM-Status#1]
This script doesn't work for me. I already tried two servers and two solusvm master servers. All i get is 'Invalid status code.'. Can you please check it out if you could fix it?

**Comment by liamjack** [comment]
Maybe they're using a different API version or authentication is failing ?

**Comment by antoniobenedetti** [comment]
It is the latest solusvm API. I have tried the script from different web servers, with or without any firewall, i get the same thing 'invalid status code.'.

**Comment by liamjack** [comment]
The current script works fine for me on WeLoveServers SolusVM API (don't know what version it is though). I did have to set the `$masterurl` to `http://` instead of `https://`, try that maybe ?

**Comment by antoniobenedetti** [comment]
Nope, same thing with `http://` :(

**Comment by liamjack** [comment]
What master server are you using ?

**Comment by antoniobenedetti** [comment]
<removed>

**Comment by liamjack** [comment]
Well their API endpoint is at the same location, try changing line 61 of index.php to `$return['message'] = "Invalid status code: {$code}";` to see what the HTTP error code is.

**Comment by antoniobenedetti** [comment]
Invalid status code: 0

**Comment by liamjack** [comment]
Could be that SSL verification is failing because no certificate chain is provided.

Try adding after line 45 of `index.php` the following line: `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);`

**Comment by antoniobenedetti** [comment]
It works fine now.

**Comment by liamjack** [comment]
Great I'll update`index.php` for everyone else. Thanks for reporting the error :)
